### ISSUE TITLE
orientation quaternion is not normalized

### ISSUE THREAD

**Issue by cocodmdr** [flynneva/bno055#18]
Hello,

I see that the orientation quaternion output of imu is not normalized : it looks like there is a factor 2**14 applied.

output of `ros2 topic echo /bno055/imu`:

```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: bno055
orientation:
  x: 535.0
  y: -275.0
  z: 4725.0
  w: -15676.0
orientation_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: -0.07777777777777778
  y: -0.027777777777777776
  z: -0.2688888888888889
angular_velocity_covariance:
- -1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: 0.061
  y: -0.059
  z: -0.03
linear_acceleration_covariance:
- -1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```

Is that normal? 
Doesn't it cause problem when using with other ROS2 nodes ?

Thank you !
